### ISSUE TITLE
多并发下批量转换页面时出现线程堵塞问题

### ISSUE THREAD

**Issue by juukee** [stonehank/html-to-md#10]
多并发下批量转换页面时一开始会成功，文件处理部分后，出现线程堵塞问题，console会自动卡住

目前发现同款 https://github.com/domchristie/turndown 这个处理无异常。

**Comment by stonehank** [comment]
有可能是报错了，目前的设定是遇到不合法html格式，例如
```
<ul>
<div>123</div>
</ul>
```
会报错而不是忽略，不清楚是否存在这种情况

**Comment by juukee** [comment]
我调试不到这种情况.... 可能要断点调试一步步看下，同步异步情况下都是会先成功一部分，然后卡住.

**Comment by stonehank** [comment]
你先用着turndown吧，那个感觉还不错，我这个可能还要花时间去弄下错误处理和格式之类的
