### ISSUE TITLE
表格内部的标签忽略后，会形成换行

### ISSUE THREAD

**Issue by Iecy** [stonehank/html-to-md#20]
表格内部的标签忽略后，会形成换行。导致表格不成型。

- 忽略内部标签的效果：

![image](https://user-images.githubusercontent.com/9412185/105469525-56db4e80-5cd3-11eb-9830-749976c95106.png)

- 不忽略内部标签的效果：
![image](https://user-images.githubusercontent.com/9412185/105469614-812d0c00-5cd3-11eb-8b9d-161547e93a64.png)

**Comment by stonehank** [comment]
@Iecy  😄 感谢告知~ 在v0.3.8版已经修复这个问题了

**Comment by Iecy** [comment]
你好，
在标签匹配的时候也会出现问题。
<td>sdfdfdfdfdf<tddfdfdfdfdfd</td>
内部出现 < 会导致解析结过有误。


在 2021年1月28日 13:57，hank<notifications@github.com> 写道：


Closed #20.

**Comment by stonehank** [comment]
@Iecy 理论上，在标签内的`<`,`>`等应该会转化为`&lt;`和`&gt;`

在v0.3.9，尝试将一些不符合规则的内容直接输出， 你可以试一下是否有其他的问题

**Comment by Iecy** [comment]
好的。感谢回复。
现在使用了自己listToMd。我这边的需求只有表格转换，接下来再试试您的组件库


在 2021年2月1日 12:56，hank<notifications@github.com> 写道：


@Iecy 理论上，在标签内的<,>等应该会转化为&lt;和&gt;
在v0.3.9，尝试将一些不符合规则的内容直接输出， 你可以试一下是否有其他的问题
