### ISSUE TITLE
\n in attributes is not handled as delimiter

### ISSUE THREAD

**Issue by BANOnotIT** [stonehank/html-to-md#33]
## The problem
If I pass this code
```html
<a href="/#tester">normal link</a> 

<a href="/#you-will-never-see-this"
moz-do-not-send="true">link from moz</a>
```
to the `html2md` method, it'll produce this code
```md
[normal link](/#tester) 
[link from moz]()
```

But if we add a space char between href and moz-specific attribute 

(like this `...ee-this"\n moz-...` or like this `...ee-this" \nmoz-...`)

it'll produce normal link:

```md
[normal link](/#tester) 
[link from moz](/#you-will-never-see-this)
```

## Possible fix
I think that the parser you use only counts spaces as attributes separators, but instead I would recomend use `' ' | '\n'`, and it might be better to use `\s` from RegExp.

**Comment by stonehank** [comment]
Thanks
Yes, the reason is only detect the `' '` inside tag attributes, now(`v0.4.4`) replace`\s` with it.
