### ISSUE TITLE
知乎部分图片提取链接有问题

### ISSUE THREAD

**Issue by hans000** [stonehank/html-to-md#43]
例如此链接里的公式图片
https://zhuanlan.zhihu.com/p/95836870

期望 https://www.zhihu.com/equation?tex=A%5Cmathbf%7Bu%7D+%3D+%5Clambda%5Cmathbf%7Bu%7D%5C%5C
实际 https://www.zhihu.com/equation?texA%5Cmathbf%7Bu%7D+%3D+%5Clambda%5Cmathbf%7Bu%7D%5C%5C

少了个=号

**Comment by stonehank** [comment]
@hans000 检测`attr=value`的时候把value内部的`=`也过滤了，已经修复并且发布 0.5.5

**Comment by hans000** [comment]
> @hans000 检测`attr=value`的时候把value内部的`=`也过滤了，已经修复并且发布 0.5.5

没有修复啊，还是不行

**Comment by stonehank** [comment]
@hans000 有更新到0.5.5吗，浏览器demo测试需要强制刷新清缓存

**Comment by hans000** [comment]
@stonehank 确实有问题，而且打包体积大了很多，90+kb了

**Comment by stonehank** [comment]
@hans000 你能不能给个测试，以下测试可以通过
```
<img src="https://www.zhihu.com/equation?tex=A%5Cmathbf%7Bu%7D+%3D+%5Clambda%5Cmathbf%7Bu%7D%5C%5C" alt="[公式]" />

转换为：

![[公式]](https://www.zhihu.com/equation?tex=A%5Cmathbf%7Bu%7D+%3D+%5Clambda%5Cmathbf%7Bu%7D%5C%5C)
```

大小和以前一样的

minified: 93KB

gzip: 10kb

**Comment by hans000** [comment]
![image](https://user-images.githubusercontent.com/26105827/150920157-20f5df01-c79e-4680-8200-44dde014c21f.png)

**Comment by stonehank** [comment]
@hans000 我忘记编译了...  发布0.5.6了
