### ISSUE TITLE
居中解析错误

### ISSUE THREAD

**Issue by chenfan0** [stonehank/html-to-md#46]
如果html标签是这样的 \<h1 align='center'>111<\/h1>,那么他会被解析成 \# 111。但是解析后md是没有居中的效果。

**Comment by stonehank** [comment]
`markdown`本身没有支持居中的语法啊，因此直接解析成 # 111 是正确的

**Comment by stonehank** [comment]
@chenfan0 这个html转换成md，没有去考虑样式问题的，一般都是用于能相互转换的页面，例如 [力扣题目](https://leetcode.cn/problems/two-sum/)，用于比较复杂的页面会显得很难看

**Comment by chenfan0** [comment]
\<h1 align='center'>111<\/h1>的效果
<h1 align='center'>111</h1>

\# 111的效果

# 111

**Comment by stonehank** [comment]
> <h1 align='center'>111</h1>的效果
> 
> # 111
> # 111的效果
> 
> # 111

我懂你的意思，但是markdown本身是不支持样式的，不能说为了样式，而直接输出一个原始html标签
