### ISSUE TITLE
上下标

### ISSUE THREAD

**Issue by libinworks** [stonehank/html-to-md#5]
还不支持 html 上标(<sup></sup>)和下标(<sub></sub>)标签。希望尽快支持自定义需求。

**Comment by stonehank** [comment]
> 还不支持 html 上标()和下标()标签。希望尽快支持自定义需求。

上下标指`sub`和`sup`标签吗，直接使用即可，`markdown`支持的

`H<sub>2</sub>O`H<sub>2</sub>O
`商标<sup>TM</sup>`商标<sup>TM</sup>
