### ISSUE TITLE
code标签class中language-*被修改

### ISSUE THREAD

**Issue by Lrunlin** [stonehank/html-to-md#50]
![image](https://user-images.githubusercontent.com/54397964/179771173-caeb9657-0f99-4cc2-ac42-d5cc0f9932c3.png)
类似这个，会出问题，js会被转为JavaScript
```js

export default 1;
```

**Comment by stonehank** [comment]
@Lrunlin 这个会造成什么问题吗，有出现报错之类的吗

有几个语言是会转为完整的格式

```js
const toStandard={
  'js':'javascript',
  'py':'python',
  'c++':'cpp',
  'md':'markdown'
}
```

**Comment by Lrunlin** [comment]
typescipt的话也没有显示

**Comment by stonehank** [comment]
@Lrunlin okok, 我没有写ts的匹配，找时间补上吧
还有就是这个demo里面的`markdown-it`插件版本太旧了，html里面没有`language-ts`这个class的，到时候一起更新下吧

**Comment by Lrunlin** [comment]
感觉可以修改成匹配到lang-和language-自动设置成``` xxx ```代码块，不在限制语言比较好

**Comment by stonehank** [comment]
@Lrunlin 确实可以考虑，但是如果人家html本身就有class，例如`class="language-small"`，那就检测到一个`small`

**Comment by Lrunlin** [comment]
> @Lrunlin 确实可以考虑，但是如果人家html本身就有class，例如`class="language-small"`，那就检测到一个`small`

一般来说用户对pre或者code设置了class="language-*"基本也可以确定是代码块了，语言的话很多高亮插件支持200多种语言，如果一个个支持的话很麻烦。如果用户对代码块有其他的配置可以考虑使用其他字符串作为前缀，language值作为代码块语言。

**Comment by stonehank** [comment]
> > @Lrunlin 确实可以考虑，但是如果人家html本身就有class，例如`class="language-small"`，那就检测到一个`small`
> 
> 一般来说用户对pre或者code设置了class="language-*"基本也可以确定是代码块了，语言的话很多高亮插件支持200多种语言，如果一个个支持的话很麻烦。如果用户对代码块有其他的配置可以考虑使用其他字符串作为前缀，language值作为代码块语言。

发布了 v0.6.0，不检测语言，直接返回匹配值

**Comment by Lrunlin** [comment]
> > > @Lrunlin确实可以考虑，如果人家html提供一个但是类，例如`class="language-small"`，那么`small`
> > 
> > 
> > 对pre或codesettingclass="class="*"基本可以确定是语言用户支持的一个高插件，200个语言如果对用户的支持很亮的话。块有其他的配置可以考虑使用其他字符串作为前缀，语言值作为代码语言块。
> 
> 发布了 v0.6.0，不检测语言，直接返回匹配值

收到了，我看下，谢谢

**Comment by septs** [comment]
我觉得应该开放一个 callback 给用户自己编程

**Comment by Lrunlin** [comment]
很不错，使用起来更加灵活了
