### ISSUE TITLE
a image没有被还原

### ISSUE THREAD

**Issue by listen80** [stonehank/html-to-md#52]
解析出来的结果没有a image,可否加上

**Comment by stonehank** [comment]
@listen80 可以给个具体例子吗

**Comment by listen80** [comment]
第二次验证，发现原因是有上层的自定义标签<test><a href='123' title=456>dddd</a></test>
会导致里面的元素丢失

**Comment by listen80** [comment]
`&lt;test>&lt;a href="123" title="456" data-turbo-frame="">dddd&lt;/a>&lt;/test>`

**Comment by listen80** [comment]
&lt;test>&lt;a href="123" title="456" data-turbo-frame="">dddd&lt;/a>&lt;/test>

**Comment by stonehank** [comment]
@listen80 发布了v0.6.1, 添加a标签的title

如果像这种`<test><a href="123" title="456" data-turbo-frame="">dddd</a></test>`有自定义标签，可以在 skipTags 添加以便跳过这个标签， 例如：`html2md(str, { skipTags: ['test'] } )`

也可以在[https://stonehank.github.io/html-to-md/](https://stonehank.github.io/html-to-md/)中尝试这些选项

**Comment by listen80** [comment]
多谢，我建议这种可以默认省略，因为不知道爬虫爬的是一些什么东西

**Comment by stonehank** [comment]
@listen80 👋 发布了 v0.7.0

目前默认还是渲染自定义标签，但是添加了一个option `renderCustomTags`， 用于全局定义自定义标签渲染方式，
可以在[https://stonehank.github.io/html-to-md/](https://stonehank.github.io/html-to-md/) 试下这个`<test><a href="123" title="456" data-turbo-frame="">dddd</a></test>`
