### ISSUE TITLE
展开 HTML 中的相对路径

### ISSUE THREAD

**Issue by septs** [stonehank/html-to-md#61]
应当通过输入 base url 参数展开所有相对路径为绝对路径

改善最终生成的 Markdown（作为独立文件存在时的）可用性

可以透过 `new URL(input, baseURL).toString()` 来实现该功能

see https://mdn.io/URL
see https://nodejs.org/dist/latest-v19.x/docs/api/url.html#the-whatwg-url-api

**Comment by stonehank** [comment]
@septs 你的意思是在处理 img, a 这些标签对url的处理？

**Comment by septs** [comment]
是的

**Comment by septs** [comment]
已更换使用 turndown
