### ISSUE TITLE
无法k解析标签

### ISSUE THREAD

**Issue by juukee** [stonehank/html-to-md#7]
无法解析以下两个标签
<html>
</body>
</body></html>

**Comment by stonehank** [comment]
> 无法解析以下两个标签

哪两个？

**Comment by juukee** [comment]
body  html
</body></html>

**Comment by stonehank** [comment]
@juukee 恩 确实，这俩确实默认情况下应该忽略，明天会修复

当前效果: `<html><body><b>abc</b></body></html>` ==> `<html><body>**abc**</body></html>`

修复后效果: `<html><body><b>abc</b></body></html>` ==> `**abc**`

**Comment by stonehank** [comment]
@juukee 已添加过滤html 和 body， 如果需要一些自定义过滤标签，可以参考[参数配置](https://github.com/stonehank/html-to-md#%E5%8F%82%E6%95%B0%E5%8F%AF%E9%80%89)
