### ISSUE TITLE
html转换md以后产生大量空行

### ISSUE THREAD

**Issue by juukee** [stonehank/html-to-md#8]
![image](https://user-images.githubusercontent.com/28680837/82133224-09d9db00-981c-11ea-9188-9f35558dff96.png)
html转换md以后，md文档产生大量空行。

**Comment by stonehank** [comment]
@juukee 麻烦贴出 html 文本

**Comment by juukee** [comment]
.`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <title>Constructs an APCIterator iterator object</title>
<link media="all" rel="stylesheet" type="text/css" href="styles/03e73060321a0a848018724a6c83de7f-theme-base.css" />
<link media="all" rel="stylesheet" type="text/css" href="styles/03e73060321a0a848018724a6c83de7f-theme-medium.css" />

 </head>
 <body class="docs"><div class="navbar navbar-fixed-top">
  <div class="navbar-inner clearfix">
    <ul class="nav" style="width: 100%">
      <li style="float: left;"><a href="class.apciterator.html">« APCIterator</a></li>
      <li style="float: right;"><a href="apciterator.current.html">APCIterator::current »</a></li>
    </ul>
  </div>
</div>
<div id="breadcrumbs" class="clearfix">
  <ul class="breadcrumbs-container">
    <li><a href="index.html">PHP Manual</a></li>
    <li><a href="class.apciterator.html">APCIterator</a></li>
    <li>Constructs an APCIterator iterator object</li>
  </ul>
</div>
<div id="layout">
  <div id="layout-content"><div id="apciterator.construct" class="refentry">
 <div class="refnamediv">
  <h1 class="refname">APCIterator::__construct</h1>
  <p class="verinfo">(PECL apc &gt;= 3.1.1)</p><p class="refpurpose"><span class="refname">APCIterator::__construct</span> &mdash; <span class="dc-title">Constructs an APCIterator iterator object</span></p>

 </div>

 <div class="refsect1 description" id="refsect1-apciterator.construct-description">
  <h3 class="title">Description</h3>
  <div class="methodsynopsis dc-description">
   <span class="modifier">public</span> <span class="methodname"><strong>APCIterator::__construct</strong></span>
    ( <span class="methodparam"><span class="type">string</span> <code class="parameter">$cache</code></span>
   [, <span class="methodparam"><span class="type"><a href="language.pseudo-types.html#language.types.mixed" class="type mixed">mixed</a></span> <code class="parameter">$search</code><span class="initializer"> = <strong><code>NULL</code></strong></span></span>
   [, <span class="methodparam"><span class="type">int</span> <code class="parameter">$format</code><span class="initializer"> = APC_ITER_ALL</span></span>
   [, <span class="methodparam"><span class="type">int</span> <code class="parameter">$chunk_size</code><span class="initializer"> = 100</span></span>
   [, <span class="methodparam"><span class="type">int</span> <code class="parameter">$list</code><span class="initializer"> = APC_LIST_ACTIVE</span></span>
  ]]]] )</div>

  <p class="para rdfs-comment">
   Constructs an <a href="class.apciterator.html" class="classname">APCIterator</a> <span class="type"><a href="language.types.object.html" class="type object">object</a></span>.
  </p>
 </div>


 <div class="refsect1 parameters" id="refsect1-apciterator.construct-parameters">
  <h3 class="title">Parameters</h3>
  <dl>

   
    <dt>
<code class="parameter">cache</code></dt>

    <dd>

     <p class="para">
      The cache type, which will be <em>user</em> or
      <em>file</em>.
     </p>
    </dd>

   
   
    <dt>
<code class="parameter">search</code></dt>

    <dd>

     <p class="para">
      A <a href="book.pcre.html" class="link">PCRE</a> regular expression that
      matches against APC key names, either as a <span class="type"><a href="language.types.string.html" class="type string">string</a></span> for
      a single regular expression, or as an <span class="type"><a href="language.types.array.html" class="type array">array</a></span> of regular
      expressions. Or, optionally pass in <strong><code>NULL</code></strong> to skip the search.
     </p>
    </dd>

   
   
    <dt>
<code class="parameter">format</code></dt>

    <dd>

     <p class="para">
      The desired format, as configured with one or more of the
      <a href="apc.constants.html" class="link">APC_ITER_*</a> constants.
     </p>
    </dd>

   
   
    <dt>
<code class="parameter">chunk_size</code></dt>

    <dd>

     <p class="para">
      The chunk size. Must be a value greater than 0. The default
      value is 100.
     </p>
    </dd>

   
   
    <dt>
<code class="parameter">list</code></dt>

    <dd>

     <p class="para">
      The type to list. Either pass in <strong><code>APC_LIST_ACTIVE</code></strong>
      or <strong><code>APC_LIST_DELETED</code></strong>.
     </p>
    </dd>

   
  </dl>

 </div>


 <div class="refsect1 returnvalues" id="refsect1-apciterator.construct-returnvalues">
  <h3 class="title">Return Values</h3>
  <p class="para">
   An <a href="class.apciterator.html" class="classname">APCIterator</a> <span class="type"><a href="language.types.object.html" class="type object">object</a></span> on success,
   or <strong><code>NULL</code></strong> on failure.
  </p>
 </div>


 <div class="refsect1 examples" id="refsect1-apciterator.construct-examples">
  <h3 class="title">Examples</h3>
  <p class="para">
   <div class="example" id="example-455">
    <p><strong>Example #1 A <span class="function"><strong>APCIterator::__construct()</strong></span> example</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br /></span><span style="color: #007700">foreach&nbsp;(new&nbsp;</span><span style="color: #0000BB">APCIterator</span><span style="color: #007700">(</span><span style="color: #DD0000">'user'</span><span style="color: #007700">,&nbsp;</span><span style="color: #DD0000">'/^counter\./'</span><span style="color: #007700">)&nbsp;as&nbsp;</span><span style="color: #0000BB">$counter</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">"</span><span style="color: #0000BB">$counter</span><span style="color: #007700">[</span><span style="color: #0000BB">key</span><span style="color: #007700">]</span><span style="color: #DD0000">:&nbsp;</span><span style="color: #0000BB">$counter</span><span style="color: #007700">[</span><span style="color: #0000BB">value</span><span style="color: #007700">]</span><span style="color: #DD0000">\n"</span><span style="color: #007700">;<br />&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #0000BB">apc_dec</span><span style="color: #007700">(</span><span style="color: #0000BB">$counter</span><span style="color: #007700">[</span><span style="color: #DD0000">'key'</span><span style="color: #007700">],&nbsp;</span><span style="color: #0000BB">$counter</span><span style="color: #007700">[</span><span style="color: #DD0000">'value'</span><span style="color: #007700">]);<br />}<br /></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
    </div>

   </div>
  </p>
 </div>


 <div class="refsect1 seealso" id="refsect1-apciterator.construct-seealso">
  <h3 class="title">See Also</h3>
  <ul class="simplelist">
   <li class="member"><span class="function"><a href="function.apc-exists.html" class="function" rel="rdfs-seeAlso">apc_exists()</a> - Checks if APC key exists</span></li>
   <li class="member"><span class="function"><a href="function.apc-cache-info.html" class="function" rel="rdfs-seeAlso">apc_cache_info()</a> - Retrieves cached information from APC's data store</span></li>
  </ul>
 </div>


</div></div></div></body></html>`

**Comment by juukee** [comment]
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <title>Constructs an APCIterator iterator object</title>
<link media="all" rel="stylesheet" type="text/css" href="styles/03e73060321a0a848018724a6c83de7f-theme-base.css" />
<link media="all" rel="stylesheet" type="text/css" href="styles/03e73060321a0a848018724a6c83de7f-theme-medium.css" />

 </head>
 <body class="docs"><div class="navbar navbar-fixed-top">
  <div class="navbar-inner clearfix">
    <ul class="nav" style="width: 100%">
      <li style="float: left;"><a href="class.apciterator.html">« APCIterator</a></li>
      <li style="float: right;"><a href="apciterator.current.html">APCIterator::current »</a></li>
    </ul>
  </div>
</div>
<div id="breadcrumbs" class="clearfix">
  <ul class="breadcrumbs-container">
    <li><a href="index.html">PHP Manual</a></li>
    <li><a href="class.apciterator.html">APCIterator</a></li>
    <li>Constructs an APCIterator iterator object</li>
  </ul>
</div>
<div id="layout">
  <div id="layout-content"><div id="apciterator.construct" class="refentry">
 <div class="refnamediv">
  <h1 class="refname">APCIterator::__construct</h1>
  <p class="verinfo">(PECL apc &gt;= 3.1.1)</p><p class="refpurpose"><span class="refname">APCIterator::__construct</span> &mdash; <span class="dc-title">Constructs an APCIterator iterator object</span></p>

 </div>

 <div class="refsect1 description" id="refsect1-apciterator.construct-description">
  <h3 class="title">Description</h3>
  <div class="methodsynopsis dc-description">
   <span class="modifier">public</span> <span class="methodname"><strong>APCIterator::__construct</strong></span>
    ( <span class="methodparam"><span class="type">string</span> <code class="parameter">$cache</code></span>
   [, <span class="methodparam"><span class="type"><a href="language.pseudo-types.html#language.types.mixed" class="type mixed">mixed</a></span> <code class="parameter">$search</code><span class="initializer"> = <strong><code>NULL</code></strong></span></span>
   [, <span class="methodparam"><span class="type">int</span> <code class="parameter">$format</code><span class="initializer"> = APC_ITER_ALL</span></span>
   [, <span class="methodparam"><span class="type">int</span> <code class="parameter">$chunk_size</code><span class="initializer"> = 100</span></span>
   [, <span class="methodparam"><span class="type">int</span> <code class="parameter">$list</code><span class="initializer"> = APC_LIST_ACTIVE</span></span>
  ]]]] )</div>

  <p class="para rdfs-comment">
   Constructs an <a href="class.apciterator.html" class="classname">APCIterator</a> <span class="type"><a href="language.types.object.html" class="type object">object</a></span>.
  </p>
 </div>


 <div class="refsect1 parameters" id="refsect1-apciterator.construct-parameters">
  <h3 class="title">Parameters</h3>
  <dl>

   
    <dt>
<code class="parameter">cache</code></dt>

    <dd>

     <p class="para">
      The cache type, which will be <em>user</em> or
      <em>file</em>.
     </p>
    </dd>

   
   
    <dt>
<code class="parameter">search</code></dt>

    <dd>

     <p class="para">
      A <a href="book.pcre.html" class="link">PCRE</a> regular expression that
      matches against APC key names, either as a <span class="type"><a href="language.types.string.html" class="type string">string</a></span> for
      a single regular expression, or as an <span class="type"><a href="language.types.array.html" class="type array">array</a></span> of regular
      expressions. Or, optionally pass in <strong><code>NULL</code></strong> to skip the search.
     </p>
    </dd>

   
   
    <dt>
<code class="parameter">format</code></dt>

    <dd>

     <p class="para">
      The desired format, as configured with one or more of the
      <a href="apc.constants.html" class="link">APC_ITER_*</a> constants.
     </p>
    </dd>

   
   
    <dt>
<code class="parameter">chunk_size</code></dt>

    <dd>

     <p class="para">
      The chunk size. Must be a value greater than 0. The default
      value is 100.
     </p>
    </dd>

   
   
    <dt>
<code class="parameter">list</code></dt>

    <dd>

     <p class="para">
      The type to list. Either pass in <strong><code>APC_LIST_ACTIVE</code></strong>
      or <strong><code>APC_LIST_DELETED</code></strong>.
     </p>
    </dd>

   
  </dl>

 </div>


 <div class="refsect1 returnvalues" id="refsect1-apciterator.construct-returnvalues">
  <h3 class="title">Return Values</h3>
  <p class="para">
   An <a href="class.apciterator.html" class="classname">APCIterator</a> <span class="type"><a href="language.types.object.html" class="type object">object</a></span> on success,
   or <strong><code>NULL</code></strong> on failure.
  </p>
 </div>


 <div class="refsect1 examples" id="refsect1-apciterator.construct-examples">
  <h3 class="title">Examples</h3>
  <p class="para">
   <div class="example" id="example-455">
    <p><strong>Example #1 A <span class="function"><strong>APCIterator::__construct()</strong></span> example</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br /></span><span style="color: #007700">foreach&nbsp;(new&nbsp;</span><span style="color: #0000BB">APCIterator</span><span style="color: #007700">(</span><span style="color: #DD0000">'user'</span><span style="color: #007700">,&nbsp;</span><span style="color: #DD0000">'/^counter\./'</span><span style="color: #007700">)&nbsp;as&nbsp;</span><span style="color: #0000BB">$counter</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">"</span><span style="color: #0000BB">$counter</span><span style="color: #007700">[</span><span style="color: #0000BB">key</span><span style="color: #007700">]</span><span style="color: #DD0000">:&nbsp;</span><span style="color: #0000BB">$counter</span><span style="color: #007700">[</span><span style="color: #0000BB">value</span><span style="color: #007700">]</span><span style="color: #DD0000">\n"</span><span style="color: #007700">;<br />&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #0000BB">apc_dec</span><span style="color: #007700">(</span><span style="color: #0000BB">$counter</span><span style="color: #007700">[</span><span style="color: #DD0000">'key'</span><span style="color: #007700">],&nbsp;</span><span style="color: #0000BB">$counter</span><span style="color: #007700">[</span><span style="color: #DD0000">'value'</span><span style="color: #007700">]);<br />}<br /></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
    </div>

   </div>
  </p>
 </div>


 <div class="refsect1 seealso" id="refsect1-apciterator.construct-seealso">
  <h3 class="title">See Also</h3>
  <ul class="simplelist">
   <li class="member"><span class="function"><a href="function.apc-exists.html" class="function" rel="rdfs-seeAlso">apc_exists()</a> - Checks if APC key exists</span></li>
   <li class="member"><span class="function"><a href="function.apc-cache-info.html" class="function" rel="rdfs-seeAlso">apc_cache_info()</a> - Retrieves cached information from APC's data store</span></li>
  </ul>
 </div>


</div></div></div></body></html>

```

**Comment by stonehank** [comment]
@juukee 试了一下，对于复杂html，目前空行存在可以保证输出的正确性，可能后续会尝试修复

**Comment by juukee** [comment]
```
<h1>h1 Heading</h1>
<h2>h2 Heading</h2>
<h3>h3 Heading</h3>
<h4>h4 Heading</h4>
<h5>h5 Heading</h5>
<h6>h6 Heading</h6>

``
```

# h1 Heading

## h2 Heading

### h3 Heading

#### h4 Heading

##### h5 Heading

###### h6 Heading

```
输出都会自动产生空行，正常来说这种不需要空行，会增加生成md文件的大量空白行.对生成的文件内容不友好

**Comment by stonehank** [comment]
空行问题需要花时间去考虑，需要添加和修改大量测试，对于md， 需要考虑每一个符号是否存在默认换行意义，例如这两个
```
// 可以紧密排列
**bold1**
##### h5 Heading
**bold2**
```

```
// 不可以紧密排列
**bold1**
* some list
**bold2**
```
